### ISSUE TITLE
testMode in commerce-gateways setting throws an error when set to false

### ISSUE THREAD

**Issue by pdaleramirez** [craftcms/commerce-paypal-checkout#37] opened 2021-06-01 10:23 UTC
testMode in commerce-gateways setting throws an error when set to false

**Comment by OwenMelbz** [comment] 2021-06-01 10:50
Duplicate of: https://github.com/craftcms/commerce-paypal-checkout/issues/22

**Closed** 2021-06-04 11:30 UTC
Labels: 🐞bug
